# Generated by Django 3.2.3 on 2022-02-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workitem',
            old_name='sliderImages1',
            new_name='sliderImage1',
        ),
        migrations.RenameField(
            model_name='workitem',
            old_name='sliderImages2',
            new_name='sliderImage2',
        ),
        migrations.RenameField(
            model_name='workitem',
            old_name='sliderImages3',
            new_name='sliderImage3',
        ),
        migrations.RenameField(
            model_name='workitem',
            old_name='sliderImages4',
            new_name='sliderImage4',
        ),
    ]
