# Generated by Django 3.2.3 on 2022-02-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20220208_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
