# Generated by Django 3.2.3 on 2022-02-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_clientcompanies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientCompanies',
            new_name='ClientCompany',
        ),
    ]
