# Generated by Django 3.2.3 on 2022-02-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_rename_clientcompanies_clientcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourwork',
            name='headerImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
