# Generated by Django 3.2.3 on 2022-03-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_ourservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='sliderVideo',
        ),
        migrations.AddField(
            model_name='workitem',
            name='videoURL',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
