# Generated by Django 3.2.3 on 2022-03-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20220308_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='videoURL',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
