# Generated by Django 3.2.12 on 2022-03-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_workitem_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='videoURL',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
