# Generated by Django 3.2.12 on 2022-03-08 08:58

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_workitem_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
