# Generated by Django 3.2.12 on 2022-03-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_workitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='youTubeLink',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
