# Generated by Django 3.2.12 on 2022-03-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_workitem_youtubelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='workDescription',
            field=models.TextField(max_length=2000),
        ),
    ]
